@startuml Caso_de_uso_1

title Diagrama de Secuencia - Registrar Producto
actor  admin
participant  "cp:ControladorProcesador"

loop "Mientras los datos sean validos y haya objetos por ingresar"

    admin -> "cp:ControladorProcesador": igresar_datos(nombre, código  categoría)
    activate "cp:ControladorProcesador"
    create ":Producto"
    alt Datos válidos


        "cp:ControladorProcesador"-> ":Producto": crear_producto(nombre, código, categoría)
        "cp:ControladorProcesador" -> "<<multiobjeto>>  lista_productos:ListaDeProductos": agregar_producto()
        activate "<<multiobjeto>>  lista_productos:ListaDeProductos"
        "<<multiobjeto>>  lista_productos:ListaDeProductos" --> "cp:ControladorProcesador": <<NULL>>
        deactivate "<<multiobjeto>>  lista_productos:ListaDeProductos"
        "cp:ControladorProcesador" --> admin: <<"Producto registrado">>
    else Datos inválidos
        "cp:ControladorProcesador" --> admin: <<"Datos invalidos">>
        deactivate "cp:ControladorProcesador"

    end

end
  note left of "<<multiobjeto>>  lista_productos:ListaDeProductos"
        El producto queda guardado y registrado en el "<<multiobjeto>>  lista_productos:ListaDeProductos"

    end note
@enduml